
atmosphere-grid:
  bottom: 0.0
  top: null
  number-of-layers: 100

photolysis-grid:
  regular-grid: true
  lower-wavelength: 92.5
  upper-wavelength: 855.0
  number-of-bins: 200

planet:
  background-gas: H2
  surface-pressure: null
  planet-mass: 5.153981e+28 # grams
  planet-radius: 1.664684e+09 # cm
  surface-albedo: 0.0
  solar-zenith-angle: 60.0
  hydrogen-escape:
    type: none
  default-gas-lower-boundary: Moses
  photon-scale-factor: 1.0
  water:
    fix-water-in-troposphere: false
    gas-rainout: false
    water-condensation: true
    condensation-rate: {A: 1.0e-5, rhc: 1, rh0: 1.05}

particles:
- name: H2SO4aer
  condensation-rate: {A: 1.0e-5, rhc: 1.0, rh0: 1.05}
- name: S8aer
  condensation-rate: {A: 1.0e-05, rhc: 1.0, rh0: 1.05}
- name: S2aer
  condensation-rate: {A: 1.0e-05, rhc: 1.0, rh0: 1.05}
- name: HCNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: HCCCNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: CH3CNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H2aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H4aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H6aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C4H4aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: N2Oaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: NH3aer
  condensation-rate: {A: 1.0e-7, rhc: 1.0, rh0: 1.05}
