
atmosphere-grid:
  bottom: 0.0
  top: null
  number-of-layers: null

photolysis-grid:
  regular-grid: true
  lower-wavelength: 92.5
  upper-wavelength: 855.0
  number-of-bins: 5 # Not worrying about photons

planet:
  background-gas: H2
  surface-pressure: null
  planet-mass: 5.153981e+28 # grams
  planet-radius: 1.664684e+09 # cm
  surface-albedo: 0.0
  solar-zenith-angle: 60.0
  hydrogen-escape:
    type: none
  default-gas-lower-boundary: Moses
  photon-scale-factor: 1.0e-100 # no photons
  water:
    fix-water-in-troposphere: false
    gas-rainout: false
    water-condensation: true
    condensation-rate: {A: 1.0e-5, rhc: 1, rh0: 1.05}
