
atmosphere-grid:
  number-of-layers: 100
  
planet:
  planet-mass: 5.153981e+28 # grams
  planet-radius: 1.664684e+09 # cm
  number-of-zenith-angles: 4
  surface-albedo: 0.06 # Following Hu et al. (2021)
  photon-scale-factor: 0.7 # Assumes 70% of radiation is reflected off of the top of the atmosphere.

optical-properties:
  ir:
    k-method: RandomOverlapResortRebin
    number-of-bins: 32
    opacities:
      k-distributions: [H2O, CO2, CO, CH4]
      CIA: [CH4-CH4, CO2-CH4, CO2-CO2, CO2-H2, H2-CH4, H2-H2, N2-H2, N2-N2, H2O-H2O, H2O-N2]
      rayleigh: true
  solar:
    k-method: RandomOverlapResortRebin
    number-of-bins: 32
    opacities:
      k-distributions: [H2O, CO2, CO, CH4]
      CIA: [CH4-CH4, CO2-CH4, CO2-CO2, CO2-H2, H2-CH4, H2-H2, N2-H2, N2-N2, H2O-H2O, H2O-N2]
      rayleigh: true
